# Generated by Django 5.2.17 on 2026-08-31 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='application',
            new_name='application_candida_79602d_idx',
            old_name='applicatio_candida_819df1_idx',
        ),
    ]
