# Generated by Django 5.2.17 on 2026-08-31 09:48

import applications.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_rename_applicatio_candida_819df1_idx_application_candida_79602d_idx'),
        ('jobs', '0003_applicationquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, upload_to=applications.validators.resume_upload_to),
        ),
        migrations.AddField(
            model_name='application',
            name='resume_original_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='ApplicationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text_snapshot', models.CharField(max_length=500)),
                ('question_type_snapshot', models.CharField(max_length=20)),
                ('options_snapshot', models.JSONField(blank=True, default=list)),
                ('value', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='applications.application')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='jobs.applicationquestion')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('application', 'question'), name='unique_answer_per_application_question')],
            },
        ),
    ]
