# Generated by Django 5.2.17 on 2026-08-31 07:06

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='job',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_employe_8985e5_idx',
            old_name='jobs_job_employer_45e924_idx',
        ),
        migrations.RenameIndex(
            model_name='job',
            new_name='jobs_job_is_acti_0f6ecf_idx',
            old_name='jobs_job_is_acti_50f26b_idx',
        ),
    ]
