# Generated by Django 5.2.17 on 2026-08-31 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('question_type', models.CharField(choices=[('TEXT', 'Text'), ('TEXTAREA', 'Textarea'), ('NUMBER', 'Number'), ('BOOLEAN', 'Boolean'), ('SINGLE_CHOICE', 'Single choice')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('options', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_questions', to='jobs.job')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['job', 'is_active', 'order'], name='jobs_applic_job_id_a7506b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('order__gte', 0)), name='question_order_non_negative')],
            },
        ),
    ]
